server:
  port: 8080
  maxHttpHeaderSize : 8192
  servlet:
    context-path: /security
spring:
  mvc:
    static-path-pattern: /**
    view:
      prefix : /
      suffix : .html
  resources:
    static-locations: classpath:/userPerceptionSystem

#=============热部署配置================
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

#==================== MySql数据源配置  ============================
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.125.209:3306/testing?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
      username: root
      password: Test@2018
#      url: jdbc:mysql://localhost:3306/testing?characterEncoding=UTF-8&useUnicode=true&useSSL=false&autoReconnect=true&failOverReadOnly=false
#      username: root
#      password: 123456

      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

#==================== redis数据源配置  ============================
  redis:
    host: 192.168.125.209
    port: 6379
    auth: Test@2018
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0

#=========文件上传配置===========
  servlet:
      multipart:
        enabled: true
        max-file-size: 100Mb
        max-request-size: 100Mb
  jta:
    atomikos:
      connectionfactory:

#==================== mybatis配置  ============================

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cmit.testing
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

#==================== webDriver配置  ============================
webDriver:
#  chrome: C:\Users\issuser\Documents\Tencent Files\648587114\FileRecv\chromedriver.exe
  chrome: E:\grid3.13\chromedriver.exe
  firefox: E:\grid3.13\geckodriver.exe
#  ie:
#  edge:
#  safari:
#  opera:

#==================== 日志配合·标准  ============================
logging:
  config: classpath:logback-boot.xml

#==================== Proxy相关配置  ============================
myproxy:
  split: ^&*
  socketPort: 8083
  readerIdleTime: 20

#==================== Fastdfs文件系统配置  ============================
fastdfs:
  maxActive: 20
  minIdle: 0
  domain: http://192.168.41.68:22122/

#==============  众测平台的url ============
task:
  #==主机+端口
    host: http://192.168.157.94:8080
  #==地址
    path: /publicSurveyTask/auth/setTaskObjIndex

#============== 定时删除fastDFS的数据  ===============================
#=== day 删除day前的数据
time: 90
