package com.cmit.testing.dao;

import com.cmit.testing.entity.SimEquipment;
import com.cmit.testing.entity.app.Device;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface SimEquipmentMapper extends BaseMapper<SimEquipment>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_equipment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_equipment
     *
     * @mbggenerated
     */
    int insert(SimEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_equipment
     *
     * @mbggenerated
     */
    int insertSelective(SimEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_equipment
     *
     * @mbggenerated
     */
    SimEquipment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_equipment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SimEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sim_equipment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimEquipment record);

    /**
     * 终端数据统计
     * @return  free：空闲，takeUp：占用，normal. onLine：在线，offLine：离线
     */
    Map<String,Long> simEquipmentCount();

    /**
     * 终端数据统计
     * @return  SMSCatCount 短信猫
     */
    Integer deviceCount();

    /**
     * 绑定的设备的手机省列表
     * @return
     */
    List<String> webProvinceCount();

    /**
     * web端空闲设备数
     * @return
     */
    Integer webFreeCount();
}