package com.cmit.testing.dao;

import com.cmit.testing.entity.SysReport;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SysReportMapper extends BaseMapper<SysReport>{

    List<SysReport> getReportAll(SysReport sysReport);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_report
     *
     * @mbggenerated
     */
    int insert(SysReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_report
     *
     * @mbggenerated
     */
    int insertSelective(SysReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_report
     *
     * @mbggenerated
     */
    SysReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysReport record);
}