package com.cmit.testing.dao;

import com.cmit.testing.entity.SysTask;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

@Mapper
public interface SysTaskMapper extends BaseMapper<SysTask>{


    List<SysTask> getSysTaskByIds(@Param("ids") Set<Integer> ids);
    /**
     *查询所有任务
     */
    List<SysTask> getAll(SysTask sysTask);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int insert(SysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int insertSelective(SysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    SysTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTask record);
}