package com.cmit.testing.entity;

import com.cmit.testing.utils.StringUtils;

import java.util.Date;

public class OrderRelationship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.chargefee_id
     *
     * @mbggenerated
     */
    private Integer chargefeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.business_name
     *
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.start_time
     *
     * @mbggenerated
     */

    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.end_time
     *
     * @mbggenerated
     */

    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.expenses_info
     *
     * @mbggenerated
     */
    private String expensesInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_relationship.phone
     *
     * @mbggenerated
     */
    private String phone;

    private String type;

    private String typeName;
    /**
     * 套餐id
     */
    private String productId;
    /**
     * 一级能开同步时间
     */
    private Date synchronizedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.id
     *
     * @return the value of order_relationship.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.id
     *
     * @param id the value for order_relationship.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.chargefee_id
     *
     * @return the value of order_relationship.chargefee_id
     * @mbggenerated
     */
    public Integer getChargefeeId() {
        return chargefeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.chargefee_id
     *
     * @param chargefeeId the value for order_relationship.chargefee_id
     * @mbggenerated
     */
    public void setChargefeeId(Integer chargefeeId) {
        this.chargefeeId = chargefeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.business_name
     *
     * @return the value of order_relationship.business_name
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.business_name
     *
     * @param businessName the value for order_relationship.business_name
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.goods_name
     *
     * @return the value of order_relationship.goods_name
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.goods_name
     *
     * @param goodsName the value for order_relationship.goods_name
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.state
     *
     * @return the value of order_relationship.state
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.state
     *
     * @param state the value for order_relationship.state
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.create_time
     *
     * @return the value of order_relationship.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.create_time
     *
     * @param createTime the value for order_relationship.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.start_time
     *
     * @return the value of order_relationship.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.start_time
     *
     * @param startTime the value for order_relationship.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.end_time
     *
     * @return the value of order_relationship.end_time
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.end_time
     *
     * @param endTime the value for order_relationship.end_time
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.expenses_info
     *
     * @return the value of order_relationship.expenses_info
     * @mbggenerated
     */
    public String getExpensesInfo() {
        return expensesInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.expenses_info
     *
     * @param expensesInfo the value for order_relationship.expenses_info
     * @mbggenerated
     */
    public void setExpensesInfo(String expensesInfo) {
        this.expensesInfo = expensesInfo == null ? null : expensesInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_relationship.phone
     *
     * @return the value of order_relationship.phone
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_relationship.phone
     *
     * @param phone the value for order_relationship.phone
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public Date getSynchronizedTime() {
        return synchronizedTime;
    }

    public void setSynchronizedTime(Date synchronizedTime) {
        this.synchronizedTime = synchronizedTime;
    }

    public String getTypeName() {
        if (StringUtils.isEmpty(type)) {
            return null;
        } else {
//            01-套餐类 02增值业务类 03服务功能类 04营销活动等其他类
            switch (type) {
                case "01":
                    return "套餐类";
                case "02":
                    return "增值业务类";
                case "03":
                    return "服务功能类";
                case "04":
                    return "营销活动等其他类";
                default:
                    return null;
            }
        }
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}