package com.cmit.testing.entity;

import java.util.ArrayList;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
import java.util.List;
import java.util.Map;

public class SimCard {

    private Double billValue;

    private Double flow;

    private Integer equipmentType;

    private Double totalPoint; //用户总积分

    private Double pointBalance; //用户可用积分

    private String consumePoint; //消费积分

    private String promotionPoint; // 促销积分

    private List<Map<String,Object>> orderStatusList = new ArrayList<>(); //筛选条件是否办理业务，0未办理，1已办理;套餐名称集合

    private Integer orderStatus;    //筛选条件是否办理业务，0未办理，1已办理

    private List<String> product = new ArrayList<>();    //套餐名称
    /**
     * 一级能开同步时间
     */
    private Date synchronizedTime;

    private Integer disableStatus;//短信猫启用sim卡状态

    public List<Map<String, Object>> getOrderStatusList() {
        return orderStatusList;
    }

    public void setOrderStatusList(List<Map<String, Object>> orderStatusList) {
        this.orderStatusList = orderStatusList;
    }

    public Integer getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Double getFlow() {
        return flow;
    }

    public void setFlow(Double flow) {
        this.flow = flow;
    }

    public Double getBillValue() {
        return billValue;
    }

    public void setBillValue(Double billValue) {
        this.billValue = billValue;
    }

    private Double minFlow;
    private Double maxFlow;

    private Double minBalance;
    private Double maxBalance;

    public String getConsumePoint() {
        return consumePoint;
    }

    public void setConsumePoint(String consumePoint) {
        this.consumePoint = consumePoint;
    }

    public String getPromotionPoint() {
        return promotionPoint;
    }

    public void setPromotionPoint(String promotionPoint) {
        this.promotionPoint = promotionPoint;
    }

    public Double getMinFlow() {
        return minFlow;
    }

    public void setMinFlow(Double minFlow) {
        this.minFlow = minFlow;
    }

    public Double getMaxFlow() {
        return maxFlow;
    }

    public void setMaxFlow(Double maxFlow) {
        this.maxFlow = maxFlow;
    }

    public Double getMinBalance() {
        return minBalance;
    }

    public void setMinBalance(Double minBalance) {
        this.minBalance = minBalance;
    }

    public Double getMaxBalance() {
        return maxBalance;
    }

    public void setMaxBalance(Double maxBalance) {
        this.maxBalance = maxBalance;
    }

    public Double getTotalPoint() {
        return totalPoint;
    }

    public Integer getEquipmentType() {
        return equipmentType;
    }

    public void setEquipmentType(Integer equipmentType) {
        this.equipmentType = equipmentType;
    }

    public void setTotalPoint(Double totalPoint) {
        this.totalPoint = totalPoint;
    }

    public Double getPointBalance() {
        return pointBalance;
    }

    public void setPointBalance(Double pointBalance) {
        this.pointBalance = pointBalance;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.service_code
     *
     * @mbggenerated
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.imsi
     *
     * @mbggenerated
     */
    private String imsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.month_cost
     *
     * @mbggenerated
     */
    private Double monthCost;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.month_cost_info
     *
     * @mbggenerated
     */
    private String monthCostInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.cancel_time
     *
     * @mbggenerated
     */

    private Date cancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.sim_host
     *
     * @mbggenerated
     */
    private String simHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.contact_info
     *
     * @mbggenerated
     */
    private String contactInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.balance
     *
     * @mbggenerated
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.available_status
     *
     * @mbggenerated
     */
    private Integer availableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_card.brand
     *
     * @mbggenerated
     */
    private String brand;


    private List<String> imsiList;

    public List<String> getImsiList() {
        return imsiList;
    }

    public void setImsiList(List<String> imsiList) {
        this.imsiList = imsiList;
    }

    private List<String> provinceList = new ArrayList<>();

    public List<String> getProvinceList() {
        return provinceList;
    }

    public void setProvinceList(List<String> provinceList) {
        this.provinceList = provinceList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.id
     *
     * @return the value of sim_card.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.id
     *
     * @param id the value for sim_card.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.operator
     *
     * @return the value of sim_card.operator
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.operator
     *
     * @param operator the value for sim_card.operator
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.province
     *
     * @return the value of sim_card.province
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.province
     *
     * @param province the value for sim_card.province
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.phone
     *
     * @return the value of sim_card.phone
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.phone
     *
     * @param phone the value for sim_card.phone
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.service_code
     *
     * @return the value of sim_card.service_code
     * @mbggenerated
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.service_code
     *
     * @param serviceCode the value for sim_card.service_code
     * @mbggenerated
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode == null ? null : serviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.imsi
     *
     * @return the value of sim_card.imsi
     * @mbggenerated
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.imsi
     *
     * @param imsi the value for sim_card.imsi
     * @mbggenerated
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.month_cost
     *
     * @return the value of sim_card.month_cost
     * @mbggenerated
     */
    public Double getMonthCost() {
        return monthCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.month_cost
     *
     * @param monthCost the value for sim_card.month_cost
     * @mbggenerated
     */
    public void setMonthCost(Double monthCost) {
        this.monthCost = monthCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.month_cost_info
     *
     * @return the value of sim_card.month_cost_info
     * @mbggenerated
     */
    public String getMonthCostInfo() {
        return monthCostInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.month_cost_info
     *
     * @param monthCostInfo the value for sim_card.month_cost_info
     * @mbggenerated
     */
    public void setMonthCostInfo(String monthCostInfo) {
        this.monthCostInfo = monthCostInfo == null ? null : monthCostInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.status
     *
     * @return the value of sim_card.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.status
     *
     * @param status the value for sim_card.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.cancel_time
     *
     * @return the value of sim_card.cancel_time
     * @mbggenerated
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.cancel_time
     *
     * @param cancelTime the value for sim_card.cancel_time
     * @mbggenerated
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.sim_host
     *
     * @return the value of sim_card.sim_host
     * @mbggenerated
     */
    public String getSimHost() {
        return simHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.sim_host
     *
     * @param simHost the value for sim_card.sim_host
     * @mbggenerated
     */
    public void setSimHost(String simHost) {
        this.simHost = simHost == null ? null : simHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.contact_info
     *
     * @return the value of sim_card.contact_info
     * @mbggenerated
     */
    public String getContactInfo() {
        return contactInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.contact_info
     *
     * @param contactInfo the value for sim_card.contact_info
     * @mbggenerated
     */
    public void setContactInfo(String contactInfo) {
        this.contactInfo = contactInfo == null ? null : contactInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.description
     *
     * @return the value of sim_card.description
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.description
     *
     * @param description the value for sim_card.description
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.balance
     *
     * @return the value of sim_card.balance
     * @mbggenerated
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.balance
     *
     * @param balance the value for sim_card.balance
     * @mbggenerated
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.available_status
     *
     * @return the value of sim_card.available_status
     * @mbggenerated
     */
    public Integer getAvailableStatus() {
        return availableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.available_status
     *
     * @param availableStatus the value for sim_card.available_status
     * @mbggenerated
     */
    public void setAvailableStatus(Integer availableStatus) {
        this.availableStatus = availableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_card.brand
     *
     * @return the value of sim_card.brand
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_card.brand
     *
     * @param brand the value for sim_card.brand
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    public List<String> getProduct() {
        return product;
    }

    public void setProduct(List<String> product) {
        this.product = product;
    }

    @Override
    public String toString() {
        return "SimCard{" +
                "billValue=" + billValue +
                ", flow=" + flow +
                ", id=" + id +
                ", operator='" + operator + '\'' +
                ", province='" + province + '\'' +
                ", phone='" + phone + '\'' +
                ", serviceCode='" + serviceCode + '\'' +
                ", imsi='" + imsi + '\'' +
                ", monthCost=" + monthCost +
                ", monthCostInfo='" + monthCostInfo + '\'' +
                ", status=" + status +
                ", cancelTime=" + cancelTime +
                ", simHost='" + simHost + '\'' +
                ", contactInfo='" + contactInfo + '\'' +
                ", description='" + description + '\'' +
                ", balance=" + balance +
                ", availableStatus=" + availableStatus +
                ", brand='" + brand + '\'' +
                ", provinceList=" + provinceList +
                ", synchronizedTime=" + synchronizedTime +
                '}';
    }

    private Integer maxMonthCost;

    private Integer minMonthCost;

    public Integer getMaxMonthCost() {
        return maxMonthCost;
    }

    public void setMaxMonthCost(Integer maxMonthCost) {
        this.maxMonthCost = maxMonthCost;
    }

    public Integer getMinMonthCost() {
        return minMonthCost;
    }

    public void setMinMonthCost(Integer minMonthCost) {
        this.minMonthCost = minMonthCost;

    }

    public Date getSynchronizedTime() {
        return synchronizedTime;
    }

    public void setSynchronizedTime(Date synchronizedTime) {
        this.synchronizedTime = synchronizedTime;
    }

    public Integer getDisableStatus() {
        return disableStatus;
    }

    public void setDisableStatus(Integer disableStatus) {
        this.disableStatus = disableStatus;
    }
}