package com.cmit.testing.entity;

import java.util.Date;

public class SimEquipment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.iphone
     *
     * @mbggenerated
     */
    private String iphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.equipment_type
     *
     * @mbggenerated
     */
    private Integer equipmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.port_name
     *
     * @mbggenerated
     */
    private String portName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.equipment_code
     *
     * @mbggenerated
     */
    private String equipmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.relation_time
     *
     * @mbggenerated
     */
    private Date relationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.available_status
     *
     * @mbggenerated
     */
    private Integer availableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_equipment.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.id
     *
     * @return the value of sim_equipment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.id
     *
     * @param id the value for sim_equipment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.iphone
     *
     * @return the value of sim_equipment.iphone
     *
     * @mbggenerated
     */
    public String getIphone() {
        return iphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.iphone
     *
     * @param iphone the value for sim_equipment.iphone
     *
     * @mbggenerated
     */
    public void setIphone(String iphone) {
        this.iphone = iphone == null ? null : iphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.equipment_type
     *
     * @return the value of sim_equipment.equipment_type
     *
     * @mbggenerated
     */
    public Integer getEquipmentType() {
        return equipmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.equipment_type
     *
     * @param equipmentType the value for sim_equipment.equipment_type
     *
     * @mbggenerated
     */
    public void setEquipmentType(Integer equipmentType) {
        this.equipmentType = equipmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.port_name
     *
     * @return the value of sim_equipment.port_name
     *
     * @mbggenerated
     */
    public String getPortName() {
        return portName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.port_name
     *
     * @param portName the value for sim_equipment.port_name
     *
     * @mbggenerated
     */
    public void setPortName(String portName) {
        this.portName = portName == null ? null : portName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.equipment_code
     *
     * @return the value of sim_equipment.equipment_code
     *
     * @mbggenerated
     */
    public String getEquipmentCode() {
        return equipmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.equipment_code
     *
     * @param equipmentCode the value for sim_equipment.equipment_code
     *
     * @mbggenerated
     */
    public void setEquipmentCode(String equipmentCode) {
        this.equipmentCode = equipmentCode == null ? null : equipmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.relation_time
     *
     * @return the value of sim_equipment.relation_time
     *
     * @mbggenerated
     */
    public Date getRelationTime() {
        return relationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.relation_time
     *
     * @param relationTime the value for sim_equipment.relation_time
     *
     * @mbggenerated
     */
    public void setRelationTime(Date relationTime) {
        this.relationTime = relationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.available_status
     *
     * @return the value of sim_equipment.available_status
     *
     * @mbggenerated
     */
    public Integer getAvailableStatus() {
        return availableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.available_status
     *
     * @param availableStatus the value for sim_equipment.available_status
     *
     * @mbggenerated
     */
    public void setAvailableStatus(Integer availableStatus) {
        this.availableStatus = availableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_equipment.status
     *
     * @return the value of sim_equipment.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_equipment.status
     *
     * @param status the value for sim_equipment.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}