package com.cmit.testing.entity;

import java.util.Date;

public class SysReport {

    private String projectName; //项目名称

    private String startTime;

    private String endTime;

    private Integer sysTaskId;//任务id

    public Integer getSysTaskId() {
        return sysTaskId;
    }

    public void setSysTaskId(Integer sysTaskId) {
        this.sysTaskId = sysTaskId;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_report.id
     *
     * @mbggenerated
     */
    private Integer id;

    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_report.report_name
     *
     * @mbggenerated
     */
    private String reportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_report.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_report.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_report.data
     *
     * @mbggenerated
     */
    private Object data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_report.id
     *
     * @return the value of sys_report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_report.id
     *
     * @param id the value for sys_report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_report.report_name
     *
     * @return the value of sys_report.report_name
     *
     * @mbggenerated
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_report.report_name
     *
     * @param reportName the value for sys_report.report_name
     *
     * @mbggenerated
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_report.create_by
     *
     * @return the value of sys_report.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_report.create_by
     *
     * @param createBy the value for sys_report.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_report.create_time
     *
     * @return the value of sys_report.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_report.create_time
     *
     * @param createTime the value for sys_report.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_report.data
     *
     * @return the value of sys_report.data
     *
     * @mbggenerated
     */
    public Object getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_report.data
     *
     * @param data the value for sys_report.data
     *
     * @mbggenerated
     */
    public void setData(Object data) {
        this.data = data;
    }


    public Integer getProjectId() {
        return projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

}