package com.cmit.testing.entity;

import java.util.Date;

public class SysSurveyTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.task_iss
     *
     * @mbggenerated
     */
    private String taskIss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.tg_accuracy
     *
     * @mbggenerated
     */
    private String tgAccuracy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.tg_clicks_avg
     *
     * @mbggenerated
     */
    private String tgClicksAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.tg_input_avg
     *
     * @mbggenerated
     */
    private String tgInputAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.tg_note_avg
     *
     * @mbggenerated
     */
    private String tgNoteAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.tg_step_avg
     *
     * @mbggenerated
     */
    private String tgStepAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.executionState
     *
     * @mbggenerated
     */
    private String executionState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.feedback
     *
     * @mbggenerated
     */
    private String feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.feedback_time
     *
     * @mbggenerated
     */
    private Date feedbackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_survey_task.msg
     *
     * @mbggenerated
     */
    private String msg;
    
    private String caseIds;
    
    private String caseState;
    
    private String root;
    
    private String body;
    
    private String header;
    
    
    public String getRoot() {
		return root;
	}

	public void setRoot(String root) {
		this.root = root== null ? null : root.trim();
	}

	public String getBody() {
		return body;
	}

	public void setBody(String body) {
		this.body = body== null ? null : body.trim();
	}

	public String getHeader() {
		return header;
	}

	public void setHeader(String header) {
		this.header = header== null ? null : header.trim();
	}

	public String getCaseIds() {
        return caseIds;
    }

    public void setCaseIds(String caseIds) {
        this.caseIds = caseIds == null ? null : caseIds.trim();
    }
    
    public String getCaseState() {
        return caseState;
    }

    public void setCaseState(String caseState) {
        this.caseState = caseState == null ? null : caseState.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.id
     *
     * @return the value of sys_survey_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.id
     *
     * @param id the value for sys_survey_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.task_id
     *
     * @return the value of sys_survey_task.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.task_id
     *
     * @param taskId the value for sys_survey_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.task_name
     *
     * @return the value of sys_survey_task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.task_name
     *
     * @param taskName the value for sys_survey_task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.task_iss
     *
     * @return the value of sys_survey_task.task_iss
     *
     * @mbggenerated
     */
    public String getTaskIss() {
        return taskIss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.task_iss
     *
     * @param taskIss the value for sys_survey_task.task_iss
     *
     * @mbggenerated
     */
    public void setTaskIss(String taskIss) {
        this.taskIss = taskIss == null ? null : taskIss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.tg_accuracy
     *
     * @return the value of sys_survey_task.tg_accuracy
     *
     * @mbggenerated
     */
    public String getTgAccuracy() {
        return tgAccuracy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.tg_accuracy
     *
     * @param tgAccuracy the value for sys_survey_task.tg_accuracy
     *
     * @mbggenerated
     */
    public void setTgAccuracy(String tgAccuracy) {
        this.tgAccuracy = tgAccuracy == null ? null : tgAccuracy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.tg_clicks_avg
     *
     * @return the value of sys_survey_task.tg_clicks_avg
     *
     * @mbggenerated
     */
    public String getTgClicksAvg() {
        return tgClicksAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.tg_clicks_avg
     *
     * @param tgClicksAvg the value for sys_survey_task.tg_clicks_avg
     *
     * @mbggenerated
     */
    public void setTgClicksAvg(String tgClicksAvg) {
        this.tgClicksAvg = tgClicksAvg == null ? null : tgClicksAvg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.tg_input_avg
     *
     * @return the value of sys_survey_task.tg_input_avg
     *
     * @mbggenerated
     */
    public String getTgInputAvg() {
        return tgInputAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.tg_input_avg
     *
     * @param tgInputAvg the value for sys_survey_task.tg_input_avg
     *
     * @mbggenerated
     */
    public void setTgInputAvg(String tgInputAvg) {
        this.tgInputAvg = tgInputAvg == null ? null : tgInputAvg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.tg_note_avg
     *
     * @return the value of sys_survey_task.tg_note_avg
     *
     * @mbggenerated
     */
    public String getTgNoteAvg() {
        return tgNoteAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.tg_note_avg
     *
     * @param tgNoteAvg the value for sys_survey_task.tg_note_avg
     *
     * @mbggenerated
     */
    public void setTgNoteAvg(String tgNoteAvg) {
        this.tgNoteAvg = tgNoteAvg == null ? null : tgNoteAvg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.tg_step_avg
     *
     * @return the value of sys_survey_task.tg_step_avg
     *
     * @mbggenerated
     */
    public String getTgStepAvg() {
        return tgStepAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.tg_step_avg
     *
     * @param tgStepAvg the value for sys_survey_task.tg_step_avg
     *
     * @mbggenerated
     */
    public void setTgStepAvg(String tgStepAvg) {
        this.tgStepAvg = tgStepAvg == null ? null : tgStepAvg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.executionState
     *
     * @return the value of sys_survey_task.executionState
     *
     * @mbggenerated
     */
    public String getExecutionState() {
        return executionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.executionState
     *
     * @param executionState the value for sys_survey_task.executionState
     *
     * @mbggenerated
     */
    public void setExecutionState(String executionState) {
        this.executionState = executionState == null ? null : executionState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.ip
     *
     * @return the value of sys_survey_task.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.ip
     *
     * @param ip the value for sys_survey_task.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.time
     *
     * @return the value of sys_survey_task.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.time
     *
     * @param time the value for sys_survey_task.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.feedback
     *
     * @return the value of sys_survey_task.feedback
     *
     * @mbggenerated
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.feedback
     *
     * @param feedback the value for sys_survey_task.feedback
     *
     * @mbggenerated
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.feedback_time
     *
     * @return the value of sys_survey_task.feedback_time
     *
     * @mbggenerated
     */
    public Date getFeedbackTime() {
        return feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.feedback_time
     *
     * @param feedbackTime the value for sys_survey_task.feedback_time
     *
     * @mbggenerated
     */
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.code
     *
     * @return the value of sys_survey_task.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.code
     *
     * @param code the value for sys_survey_task.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_survey_task.msg
     *
     * @return the value of sys_survey_task.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_survey_task.msg
     *
     * @param msg the value for sys_survey_task.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}