package com.cmit.testing.entity;

import java.util.Date;
import java.util.List;
import java.util.Map;

public class TestCase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.id
     *
     * @mbggenerated
     */
    private Integer id;

    private Integer sysTaskId;

    private Integer bSysTaskId;//业务任务id

    private String type;

    private int phoneNumber;//电话号码个数

    private Integer executeNumber; //执行的总次数

    public Integer getExecuteNumber() {
        if(executeNumber == null ){
            return 0;
        }
        return executeNumber;
    }

    public void setExecuteNumber(Integer executeNumber) {
        this.executeNumber = executeNumber;
    }

    public int getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    private List<Integer> unequalFinshs;    //isFinish不等于什么

    private Integer surveyTaskId; //众测任务id

    public Integer getSurveyTaskId() {
        return surveyTaskId;
    }

    public void setSurveyTaskId(Integer surveyTaskId) {
        this.surveyTaskId = surveyTaskId;
    }

    public Integer getSysTaskId() {
        return sysTaskId;
    }

    public void setSysTaskId(Integer sysTaskId) {
        this.sysTaskId = sysTaskId;
    }

    public Integer getbSysTaskId() {
        return bSysTaskId;
    }

    public void setbSysTaskId(Integer bSysTaskId) {
        this.bSysTaskId = bSysTaskId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.script_id
     *
     * @mbggenerated
     */
    private Integer scriptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.retry
     *
     * @mbggenerated
     */
    private Integer retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.follow_id
     *
     * @mbggenerated
     */
    private String followId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.is_finish
     *
     * @mbggenerated
     */
    private Integer isFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.information
     *
     * @mbggenerated
     */
    private String information;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.is_record
     *
     * @mbggenerated
     */
    private Integer isRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.success_num
     *
     * @mbggenerated
     */
    private Integer successNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.failure_num
     *
     * @mbggenerated
     */
    private Integer failureNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.success_rate
     *
     * @mbggenerated
     */
    private Double successRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.code
     *
     * @mbggenerated
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.execution_type
     *
     * @mbggenerated
     */
    private Integer executionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.execution_date
     *
     * @mbggenerated
     */
    private String executionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.excute_num
     *
     * @mbggenerated
     */
    private Integer excuteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.old_testcase_id
     *
     * @mbggenerated
     */
    private Integer oldTestcaseId;

    private List<Parameter> params;

    private String flag;

    private Integer isMerge;

    private String businessName;

    public List<Parameter> getParams() {
        return params;
    }

    public void setParams(List<Parameter> params) {
        this.params = params;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.merge_num
     *
     * @mbggenerated
     */
    private Integer mergeNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.id
     *
     * @return the value of testcase.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.id
     *
     * @param id the value for testcase.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.serial_number
     *
     * @return the value of testcase.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.serial_number
     *
     * @param serialNumber the value for testcase.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.name
     *
     * @return the value of testcase.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.name
     *
     * @param name the value for testcase.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.business_id
     *
     * @return the value of testcase.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.business_id
     *
     * @param businessId the value for testcase.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.script_id
     *
     * @return the value of testcase.script_id
     *
     * @mbggenerated
     */
    public Integer getScriptId() {
        return scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.script_id
     *
     * @param scriptId the value for testcase.script_id
     *
     * @mbggenerated
     */
    public void setScriptId(Integer scriptId) {
        this.scriptId = scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.retry
     *
     * @return the value of testcase.retry
     *
     * @mbggenerated
     */
    public Integer getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.retry
     *
     * @param retry the value for testcase.retry
     *
     * @mbggenerated
     */
    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.follow_id
     *
     * @return the value of testcase.follow_id
     *
     * @mbggenerated
     */
    public String getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.follow_id
     *
     * @param followId the value for testcase.follow_id
     *
     * @mbggenerated
     */
    public void setFollowId(String followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.is_finish
     *
     * @return the value of testcase.is_finish
     *
     * @mbggenerated
     */
    public Integer getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.is_finish
     *
     * @param isFinish the value for testcase.is_finish
     *
     * @mbggenerated
     */
    public void setIsFinish(Integer isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.information
     *
     * @return the value of testcase.information
     *
     * @mbggenerated
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.information
     *
     * @param information the value for testcase.information
     *
     * @mbggenerated
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.is_record
     *
     * @return the value of testcase.is_record
     *
     * @mbggenerated
     */
    public Integer getIsRecord() {
        return isRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.is_record
     *
     * @param isRecord the value for testcase.is_record
     *
     * @mbggenerated
     */
    public void setIsRecord(Integer isRecord) {
        this.isRecord = isRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.create_time
     *
     * @return the value of testcase.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.create_time
     *
     * @param createTime the value for testcase.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.create_by
     *
     * @return the value of testcase.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.create_by
     *
     * @param createBy the value for testcase.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.update_time
     *
     * @return the value of testcase.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.update_time
     *
     * @param updateTime the value for testcase.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.update_by
     *
     * @return the value of testcase.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.update_by
     *
     * @param updateBy the value for testcase.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.success_num
     *
     * @return the value of testcase.success_num
     *
     * @mbggenerated
     */
    public Integer getSuccessNum() {
        return successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.success_num
     *
     * @param successNum the value for testcase.success_num
     *
     * @mbggenerated
     */
    public void setSuccessNum(Integer successNum) {
        this.successNum = successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.failure_num
     *
     * @return the value of testcase.failure_num
     *
     * @mbggenerated
     */
    public Integer getFailureNum() {
        return failureNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.failure_num
     *
     * @param failureNum the value for testcase.failure_num
     *
     * @mbggenerated
     */
    public void setFailureNum(Integer failureNum) {
        this.failureNum = failureNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.success_rate
     *
     * @return the value of testcase.success_rate
     *
     * @mbggenerated
     */
    public Double getSuccessRate() {
        return successRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.success_rate
     *
     * @param successRate the value for testcase.success_rate
     *
     * @mbggenerated
     */
    public void setSuccessRate(Double successRate) {
        this.successRate = successRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.code
     *
     * @return the value of testcase.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.code
     *
     * @param code the value for testcase.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.execution_type
     *
     * @return the value of testcase.execution_type
     *
     * @mbggenerated
     */
    public Integer getExecutionType() {
        return executionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.execution_type
     *
     * @param executionType the value for testcase.execution_type
     *
     * @mbggenerated
     */
    public void setExecutionType(Integer executionType) {
        this.executionType = executionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.execution_date
     *
     * @return the value of testcase.execution_date
     *
     * @mbggenerated
     */
    public String getExecutionDate() {
        return executionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.execution_date
     *
     * @param executionDate the value for testcase.execution_date
     *
     * @mbggenerated
     */
    public void setExecutionDate(String executionDate) {
        this.executionDate = executionDate == null ? null : executionDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.excute_num
     *
     * @return the value of testcase.excute_num
     *
     * @mbggenerated
     */
    public Integer getExcuteNum() {
        return excuteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.excute_num
     *
     * @param excuteNum the value for testcase.excute_num
     *
     * @mbggenerated
     */
    public void setExcuteNum(Integer excuteNum) {
        this.excuteNum = excuteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.old_testcase_id
     *
     * @return the value of testcase.old_testcase_id
     *
     * @mbggenerated
     */
    public Integer getOldTestcaseId() {
        return oldTestcaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.old_testcase_id
     *
     * @param oldTestcaseId the value for testcase.old_testcase_id
     *
     * @mbggenerated
     */
    public void setOldTestcaseId(Integer oldTestcaseId) {
        this.oldTestcaseId = oldTestcaseId;
    }


    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.is_merge
     *
     * @return the value of testcase.is_merge
     *
     * @mbggenerated
     */
    public Integer getIsMerge() {
        return isMerge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.is_merge
     *
     * @param isMerge the value for testcase.is_merge
     *
     * @mbggenerated
     */
    public void setIsMerge(Integer isMerge) {
        this.isMerge = isMerge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.merge_num
     *
     * @return the value of testcase.merge_num
     *
     * @mbggenerated
     */
    public Integer getMergeNum() {
        return mergeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.merge_num
     *
     * @param mergeNum the value for testcase.merge_num
     *
     * @mbggenerated
     */
    public void setMergeNum(Integer mergeNum) {
        this.mergeNum = mergeNum;
    }

    public String getBusinessName() {
        return businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public List<Integer> getUnequalFinshs() {
        return unequalFinshs;
    }

    public void setUnequalFinshs(List<Integer> unequalFinshs) {
        this.unequalFinshs = unequalFinshs;
    }
}